In [1]:
import load
import numpy as np
import matplotlib
matplotlib.use("Qt5Agg")
import matplotlib.pyplot as plt

In [69]:
import tree
gcat = tree.halomodule.Halo(nout=782, is_gal=True)

[Halo.load_info] loading info
[Halo.load_info] nout = 782, base =./


In [5]:
s = load.sim.Sim(nout=782)

[sim._hilbert_cpulist] No AMR instance,
[sim._hilbert_cpulist] Loading one...
An AMR instance is created
 Sim
An AMR instance is created
 Sim
Simulation set up.


In [70]:
gg1 = load.rd_GM.Gal(782, catalog=gcat.data[4], info=s.info)
gg1.debug=False
mk_gal(gg1)
gg1.cal_norm_vec()
#gg1.meta.nvec

info <load.info.Info object at 0x7ff23d3233c8>
File Not Found: ./halo/HAL_00782/hal_dms_0000005
No DM data loaded
File Not Found: ./GalaxyMaker/CELL_00782/gal_cells_0000005
No CELL data loaded
catalog center 45.4466552734375 -50.32125473022461 -16.45562744140625
star x [ 45.449  45.443  45.494 ...,  45.45   45.45   45.448]
star x [  2.796  -3.525  47.333 ...,   3.521   3.613   1.667]
gal.debug False


array([ 0.728,  0.681, -0.081])

In [71]:
gg2 = load.rd_GM.Gal(782, catalog=gcat.data[154], info=s.info)
gg2.debug=False
mk_gal(gg2)
gg2.cal_norm_vec()
#gg2.meta.nvec

info <load.info.Info object at 0x7ff23d3233c8>
File Not Found: ./halo/HAL_00782/hal_dms_0000155
No DM data loaded
File Not Found: ./GalaxyMaker/CELL_00782/gal_cells_0000155
No CELL data loaded
catalog center -19.426969528198242 -27.764034271240234 55.44676971435547
star x [-19.433 -19.427 -19.436 ..., -19.424 -19.426 -19.428]
star x [-6.231 -0.326 -8.995 ...,  3.101  0.526 -0.834]
gal.debug False


array([ 0.726,  0.325, -0.606])

In [79]:
fig, ax = plt.subplots()
ax.hist2d(np.concatenate((gg1.star["x"]-65, gg2.star["x"])),
           np.concatenate((gg1.star["y"]+22.5, gg2.star["y"])),
           weights=np.concatenate((gg1.star["m"], gg2.star["m"])),
           bins=100)
patch =Arrow(0, 0,
             gg2.meta.nvec[0]*30,
             gg2.meta.nvec[1]*30, width=4.0)
ax.add_patch(patch)
#plt.show()

In [65]:
from makegal import *

In [48]:
from matplotlib.pyplot import Arrow

In [74]:
gg2.meta.nvec

array([ 0.726,  0.325, -0.606])

In [80]:
fig, ax = plt.subplots()
ax.add_patch(Arrow(-11971.5690613, 21085.0448608,
                   -11996.4625223, 21070.5452283))


In [83]:
plt.show()

In [82]:
fig, ax = plt.subplots()
ax.add_patch(Arrow(-1., 2,
                   4., 4))
