In [1]:
import numpy as np
a = np.array([0,1,2,3,4])

In [8]:
print("datatype:", type(a), a.dtype)
print(a.itemsize)
print(a.shape)
print(np.shape(a))
print(a.size)
print(np.size(a))
print(a.nbytes)

datatype: <class 'numpy.ndarray'> int64
8
(5,)
(5,)
5
5
40


In [9]:
a.fill(123)
print(a)

[123 123 123 123 123]


In [10]:
a[:] = 321
print(a)

[321 321 321 321 321]


#### Slicing

In [18]:
a = np.array([10,11,12,13,14,15,16])
print(a[1:3])
print("negative index")
print(a[3:-3])
print(a[:3])
print(a[3:])

[11 12]
negative index
[13]
[10 11 12]
[13 14 15 16]


In [20]:
print("STEP")
print("every other element", a[::2])
print("every third element", a[::3])
print("starting from the first", a[1::2])

STEP
every other element [10 12 14 16]
every third element [10 13 16]
starting from the first [11 13 15]


#### Multi-dimensional

In [27]:
a = np.array([[0,1, 2, 3, 4],
              [8,9,10,11,12]])
print(a.shape)
print(a.size)
print(a.ndim)

(2, 5)
10
2


In [28]:
print(a[1,2])
print(a[-1,3])
print(a[1])

10
11
[ 8  9 10 11 12]


#### Indexing