In [18]:
import numpy as np

a = np.array([1,2,3,3,2,1,1,1,2,1,3,3,2,1,3,2,3,1,3,2])
b = np.random.rand(len(a))

In [24]:
class dummy():
    def __init__(self,a,b):
        self.a = a
        self.b = b

In [25]:
alist=[]
for aa,bb in zip(a,b):
    alist.append(dummy(aa,bb))

In [27]:
sorted_ab = sorted(alist, key = lambda x: (x.a, x.b))

In [29]:
for aabb in sorted_ab:
    print(aabb.a, aabb.b)

1 0.0706960437428
1 0.152503894019
1 0.284759956809
1 0.497058553157
1 0.698375042323
1 0.732521626174
1 0.779797503616
2 0.26582220244
2 0.335984959373
2 0.581835371869
2 0.647907681252
2 0.73526417698
2 0.878657852374
3 0.210454560062
3 0.306363524519
3 0.309796016108
3 0.460793805609
3 0.603566653545
3 0.681647184262
3 0.68479683659


In [19]:
ab = np.stack((a,b)).T

In [20]:
sorted_ab = sorted(ab, key = lambda x: (x[0], x[1]))

In [21]:
sorted_ab

[array([ 1.        ,  0.07069604]),
 array([ 1.        ,  0.15250389]),
 array([ 1.        ,  0.28475996]),
 array([ 1.        ,  0.49705855]),
 array([ 1.        ,  0.69837504]),
 array([ 1.        ,  0.73252163]),
 array([ 1.       ,  0.7797975]),
 array([ 2.       ,  0.2658222]),
 array([ 2.        ,  0.33598496]),
 array([ 2.        ,  0.58183537]),
 array([ 2.        ,  0.64790768]),
 array([ 2.        ,  0.73526418]),
 array([ 2.        ,  0.87865785]),
 array([ 3.        ,  0.21045456]),
 array([ 3.        ,  0.30636352]),
 array([ 3.        ,  0.30979602]),
 array([ 3.        ,  0.46079381]),
 array([ 3.        ,  0.60356665]),
 array([ 3.        ,  0.68164718]),
 array([ 3.        ,  0.68479684])]